#import "CueCards.h"
#import "MusicPlayer.h"
#import "MusicAPI.h"
#import "MusicBridge.h"
#import "NativeNavigationUI.h"
#import "ExperimentalOTAFlash.h"
#import "music.h"
#import <AVFoundation/AVFoundation.h>
#import <MediaPlayer/MediaPlayer.h>
#import <ImageIO/ImageIO.h>
static NSString *String(id v){return [v isKindOfClass:NSString.class]?v:@"";}
static NSDictionary *Song(id value){if(![value isKindOfClass:NSDictionary.class]||![value[@"id"]isKindOfClass:NSNumber.class])return nil;id album=value[@"al"]?:value[@"album"];if(![album isKindOfClass:NSDictionary.class])album=@{};id artists=value[@"ar"]?:value[@"artists"];NSMutableArray *names=[NSMutableArray new];if([artists isKindOfClass:NSArray.class])for(id a in artists)if([a isKindOfClass:NSDictionary.class]&&String(a[@"name"]).length)[names addObject:a[@"name"]];return @{@"id":value[@"id"],@"name":String(value[@"name"]),@"artist":String(value[@"artist"]).length?value[@"artist"]:[names componentsJoinedByString:@" / "],@"cover":String(value[@"cover"]).length?value[@"cover"]:String(album[@"picUrl"]),@"duration":@([value[@"dt"]?:value[@"duration"] doubleValue])};}
static NSURL *MediaURL(NSString *s){NSURLComponents *c=[NSURLComponents componentsWithString:s];NSString *h=c.host.lowercaseString;if(!h||!( [h hasSuffix:@".126.net"]||[h hasSuffix:@".163.com"]||[h isEqual:@"music.163.com"])||c.user||c.password)return nil;if([c.scheme isEqual:@"http"])c.scheme=@"https";return [c.scheme isEqual:@"https"]?c.URL:nil;}
static NSData *Gray(UIImage *image){if(!image.CGImage)return nil;NSMutableData *d=[NSMutableData dataWithLength:TM_COVER_BYTES];CGColorSpaceRef cs=CGColorSpaceCreateDeviceGray();CGContextRef ctx=CGBitmapContextCreate(d.mutableBytes,144,144,8,144,cs,kCGImageAlphaNone);CGColorSpaceRelease(cs);if(!ctx)return nil;CGContextSetInterpolationQuality(ctx,kCGInterpolationHigh);CGContextDrawImage(ctx,CGRectMake(0,0,144,144),image.CGImage);CGContextRelease(ctx);return d;}
@implementation TMPlayer{
 AVPlayer *_player;id _timeObserver;NSArray *_queue,*_lyrics;NSDictionary *_song;UIImage *_cover;NSData *_gray;NSString *_status;TMMusicBridge *_bridge;NSTimer *_timer;
 NSUInteger _ticket,_sentTicket;uint32_t _request;BOOL _glasses;NSInteger _mode;double _duration;id _endObserver;BOOL _wantsPlay;
}
+ (instancetype)shared{static TMPlayer *p;static dispatch_once_t once;dispatch_once(&once,^{p=[self new];});return p;}
- (instancetype)init{if((self=[super init])){_player=[AVPlayer new];_bridge=[TMMusicBridge new];_mode=[NSUserDefaults.standardUserDefaults integerForKey:@"TurboMusicDisplayModeV1"];_mode=MAX(0,MIN(2,_mode));_glasses=[NSUserDefaults.standardUserDefaults boolForKey:@"TurboMusicGlassesV1"];_status=@"搜索歌曲，或先播放本机校验曲";
 __weak typeof(self) weak=self;_bridge.snapshot=^NSDictionary *{TMPlayer *s=weak;if(!s)return @{};return @{@"title":s.song[@"name"]?:@"",@"artist":s.song[@"artist"]?:@"",@"position":@((uint32_t)(s.position*1000)),@"duration":@((uint32_t)(s.duration*1000)),@"playing":@(s.playing),@"mode":@(s.mode),@"request":@(s->_request)};};
 _bridge.command=^(NSDictionary *q){TMPlayer *s=weak;if(!s)return;unsigned e=[q[@"event"]unsignedIntValue];s->_request=[q[@"request"]unsignedIntValue];if(e==TM_VIEW_CLOSED)return;
  if(e==TM_RESUME){if(s->_song){[s play:YES];[s showOnGlasses];}else {NSDictionary *last=[NSUserDefaults.standardUserDefaults dictionaryForKey:@"TurboMusicLastSongV1"];if(last){[s setGlasses:YES];[s playSong:last queue:@[last]];}else s->_status=@"眼镜请求播放；请先在手机选歌";}return;}
  if(e==TM_PLAY)[s play:YES];else if(e==TM_PAUSE)[s play:NO];else if(e==TM_NEXT)[s step:1];else if(e==TM_PREV)[s step:-1];
 };
 _timer=[NSTimer scheduledTimerWithTimeInterval:.15 repeats:YES block:^(NSTimer *t){TMPlayer *s=weak;if(s)[s->_bridge pump];}];
 _timeObserver=[_player addPeriodicTimeObserverForInterval:CMTimeMakeWithSeconds(.25,600) queue:dispatch_get_main_queue() usingBlock:^(CMTime time){[weak refresh];}];
 [_player addObserver:self forKeyPath:@"timeControlStatus" options:0 context:NULL];[_player addObserver:self forKeyPath:@"currentItem.status" options:0 context:NULL];
 [NSNotificationCenter.defaultCenter addObserver:self selector:@selector(interrupt:) name:AVAudioSessionInterruptionNotification object:nil];[NSNotificationCenter.defaultCenter addObserver:self selector:@selector(route:) name:AVAudioSessionRouteChangeNotification object:nil];
 MPRemoteCommandCenter *r=MPRemoteCommandCenter.sharedCommandCenter;[r.playCommand addTargetWithHandler:^MPRemoteCommandHandlerStatus(MPRemoteCommandEvent *e){dispatch_async(dispatch_get_main_queue(),^{[weak play:YES];});return MPRemoteCommandHandlerStatusSuccess;}];[r.pauseCommand addTargetWithHandler:^MPRemoteCommandHandlerStatus(MPRemoteCommandEvent *e){dispatch_async(dispatch_get_main_queue(),^{[weak play:NO];});return MPRemoteCommandHandlerStatusSuccess;}];[r.nextTrackCommand addTargetWithHandler:^MPRemoteCommandHandlerStatus(MPRemoteCommandEvent *e){dispatch_async(dispatch_get_main_queue(),^{[weak step:1];});return MPRemoteCommandHandlerStatusSuccess;}];[r.previousTrackCommand addTargetWithHandler:^MPRemoteCommandHandlerStatus(MPRemoteCommandEvent *e){dispatch_async(dispatch_get_main_queue(),^{[weak step:-1];});return MPRemoteCommandHandlerStatusSuccess;}];
 }return self;}
- (NSDictionary *)song{return _song;}- (NSArray *)lyrics{return _lyrics?:@[];}- (UIImage *)cover{return _cover;}
- (BOOL)playing{return _player.timeControlStatus==AVPlayerTimeControlStatusPlaying;}
- (double)position{double n=CMTimeGetSeconds(_player.currentTime);return isfinite(n)?MAX(0,n):0;}
- (double)duration{double n=CMTimeGetSeconds(_player.currentItem.duration);return isfinite(n)&&n>0?n:_duration;}
- (NSString *)status{return _status?:@"";}- (NSString *)bridgeStatus{return _bridge.note;}
- (NSInteger)mode{return _mode;}- (void)setMode:(NSInteger)m{_mode=MAX(0,MIN(2,m));[NSUserDefaults.standardUserDefaults setInteger:_mode forKey:@"TurboMusicDisplayModeV1"];}
- (BOOL)glasses{return _glasses;}- (void)setGlasses:(BOOL)v{_glasses=v;[NSUserDefaults.standardUserDefaults setBool:v forKey:@"TurboMusicGlassesV1"];if(v&&_song)[self showOnGlasses];else if(!v)[_bridge close];}
- (void)observeValueForKeyPath:(NSString *)k ofObject:(id)object change:(NSDictionary *)change context:(void *)context{if(_player.currentItem.status==AVPlayerItemStatusFailed){_status=@"播放失败：媒体地址可能已失效，请重新选歌";_wantsPlay=NO;}else if(_player.timeControlStatus==AVPlayerTimeControlStatusWaitingToPlayAtSpecifiedRate)_status=@"正在缓冲（歌词时钟已暂停）";else if(self.playing)_status=@"播放中";[_bridge changed];[self refresh];}
- (void)interrupt:(NSNotification *)n{if([n.userInfo[AVAudioSessionInterruptionTypeKey]unsignedIntegerValue]==AVAudioSessionInterruptionTypeBegan){[self play:NO];_status=@"音频被其他任务中断，点击播放恢复";}}
- (void)route:(NSNotification *)n{if([n.userInfo[AVAudioSessionRouteChangeReasonKey]unsignedIntegerValue]==AVAudioSessionRouteChangeReasonOldDeviceUnavailable){[self play:NO];_status=@"音频设备断开，已暂停";}}
- (void)play:(BOOL)v{if(!v){_wantsPlay=NO;[_player pause];_status=@"已暂停";[self refresh];return;}if(!_player.currentItem){_status=@"请先选择歌曲";return;}NSError *error=nil;AVAudioSession *audio=AVAudioSession.sharedInstance;if(![audio setCategory:AVAudioSessionCategoryPlayback mode:AVAudioSessionModeDefault options:0 error:&error]||![audio setActive:YES error:&error]){_status=@"无法取得音频输出，请先结束对话/录音";return;}_wantsPlay=YES;[_player play];}
- (void)seek:(double)s{if(!isfinite(s)||!_player.currentItem)return;[_player seekToTime:CMTimeMakeWithSeconds(MAX(0,MIN(self.duration,s)),600) toleranceBefore:kCMTimeZero toleranceAfter:kCMTimeZero completionHandler:^(BOOL done){dispatch_async(dispatch_get_main_queue(),^{[self->_bridge changed];});}];}
- (void)step:(NSInteger)d{if(!_queue.count)return;NSUInteger index=[_queue indexOfObjectPassingTest:^BOOL(id v,NSUInteger i,BOOL *stop){return [v[@"id"]isEqual:self->_song[@"id"]];}];if(index==NSNotFound)index=0;NSInteger next=((NSInteger)index+d+(NSInteger)_queue.count)%(NSInteger)_queue.count;[self playSong:_queue[next] queue:_queue];}
- (void)refresh{if(!_song)return;NSMutableDictionary *now=[@{MPMediaItemPropertyTitle:_song[@"name"]?:@"",MPMediaItemPropertyArtist:_song[@"artist"]?:@"",MPMediaItemPropertyPlaybackDuration:@(self.duration),MPNowPlayingInfoPropertyElapsedPlaybackTime:@(self.position),MPNowPlayingInfoPropertyPlaybackRate:@(self.playing?1:0)}mutableCopy];if(_cover){UIImage *im=_cover;now[MPMediaItemPropertyArtwork]=[[MPMediaItemArtwork alloc]initWithBoundsSize:im.size requestHandler:^UIImage *(CGSize s){return im;}];}MPNowPlayingInfoCenter.defaultCenter.nowPlayingInfo=now;}
- (void)installURL:(NSURL *)url ticket:(NSUInteger)ticket{if(ticket!=_ticket)return;if(_endObserver)[NSNotificationCenter.defaultCenter removeObserver:_endObserver];AVPlayerItem *item=[AVPlayerItem playerItemWithURL:url];[_player replaceCurrentItemWithPlayerItem:item];__weak typeof(self) weak=self;_endObserver=[NSNotificationCenter.defaultCenter addObserverForName:AVPlayerItemDidPlayToEndTimeNotification object:item queue:NSOperationQueue.mainQueue usingBlock:^(NSNotification *n){TMPlayer *s=weak;if(!s||ticket!=s->_ticket)return;if(s->_queue.count>1)[s step:1];else [s play:NO];}];[self play:YES];if(_glasses)[self showOnGlasses];}
- (void)playSong:(NSDictionary *)value queue:(NSArray *)queue{NSDictionary *s=Song(value);if(!s)return;NSUInteger ticket=++_ticket;[_player pause];_song=s;NSMutableArray *q=[NSMutableArray new];for(id v in queue){id x=Song(v);if(x)[q addObject:x];}_queue=q.count?q:@[s];_duration=[s[@"duration"]doubleValue]/1000;_cover=nil;_gray=nil;_lyrics=@[];_status=@"正在获取播放地址";[NSUserDefaults.standardUserDefaults setObject:s forKey:@"TurboMusicLastSongV1"];
 [[TMMusicAPI shared]request:@"/api/song/enhance/player/url/v1" payload:@{@"ids":[NSString stringWithFormat:@"[%@]",s[@"id"]],@"level":@"standard",@"encodeType":@"aac"} eapi:YES done:^(NSDictionary *j,NSString *err){if(ticket!=self->_ticket)return;NSArray *a=[j[@"data"]isKindOfClass:NSArray.class]?j[@"data"]:@[];NSDictionary *v=[a.firstObject isKindOfClass:NSDictionary.class]?a.firstObject:@{};NSURL *url=MediaURL(String(v[@"url"]));if(err||!url){self->_status=err?:@"账号没有可播放地址，请登录或选择可播放歌曲（不绕过会员限制）";return;}self->_status=v[@"freeTrialInfo"]&&v[@"freeTrialInfo"]!=NSNull.null?@"当前账号仅可试听":@"准备播放";[self installURL:url ticket:ticket];}];
 [[TMMusicAPI shared]request:@"/api/song/lyric" payload:@{@"id":s[@"id"],@"lv":@-1,@"kv":@-1,@"tv":@-1} eapi:NO done:^(NSDictionary *j,NSString *err){if(ticket!=self->_ticket)return;id l=[j[@"lrc"]isKindOfClass:NSDictionary.class]?j[@"lrc"]:@{};self->_lyrics=TMParseLRC(String(l[@"lyric"]));if(!self->_lyrics.count)self->_lyrics=@[@{@"ms":@0,@"text":err?@"歌词获取失败，可继续播放":@"纯音乐或暂无歌词"}];[self->_bridge assetsCover:nil lyrics:self->_lyrics];}];
 NSURL *cover=MediaURL(s[@"cover"]);if(cover){[[NSURLSession.sharedSession dataTaskWithURL:cover completionHandler:^(NSData *d,NSURLResponse *r,NSError *e){if(e||d.length>8*1024*1024)return;CGImageSourceRef source=CGImageSourceCreateWithData((__bridge CFDataRef)d,NULL);if(!source)return;CGImageRef image=CGImageSourceCreateThumbnailAtIndex(source,0,(__bridge CFDictionaryRef)@{(__bridge id)kCGImageSourceCreateThumbnailFromImageAlways:@YES,(__bridge id)kCGImageSourceThumbnailMaxPixelSize:@360,(__bridge id)kCGImageSourceCreateThumbnailWithTransform:@YES});CFRelease(source);UIImage *im=image?[UIImage imageWithCGImage:image]:nil;if(image)CGImageRelease(image);NSData *gray=Gray(im);dispatch_async(dispatch_get_main_queue(),^{if(ticket!=self->_ticket)return;self->_cover=im;self->_gray=gray;[self->_bridge assetsCover:gray lyrics:nil];});}]resume];}
}
- (void)showOnGlasses{if(!_song)return;if(!TCCueCardsPause()||!TNVPauseForOTA()||[TIOOTAFlashStatus()[@"stage"]unsignedIntegerValue]){_status=@"导航或固件传输占用通道，请先结束";return;}if(_sentTicket==_ticket)[_bridge reopen];else{_sentTicket=_ticket;[_bridge openWithCover:_gray lyrics:_lyrics];}}
- (void)hideGlasses{[_bridge close];}
- (void)demo{NSUInteger ticket=++_ticket;_song=@{@"id":@0,@"name":@"夜航 · 本机校验 7392",@"artist":@"Turbo Lab · 合成测试音",@"duration":@90000};_queue=@[];_duration=90;_lyrics=@[@{@"ms":@0,@"text":@"音乐画面校验 7392"},@{@"ms":@5000,@"text":@"城市的灯渐渐远去"},@{@"ms":@10000,@"text":@"沿着星光 慢慢向前"},@{@"ms":@15000,@"text":@"让晚风带我到明天"},@{@"ms":@25000,@"text":@"旋钮切歌 · 按键播放暂停"},@{@"ms":@35000,@"text":@"关闭画面，音乐继续"},@{@"ms":@55000,@"text":@"手机拖动进度，歌词同步"},@{@"ms":@75000,@"text":@"校验结束 8642"}];
 UIGraphicsImageRendererFormat *f=[UIGraphicsImageRendererFormat defaultFormat];f.scale=1;_cover=[[[UIGraphicsImageRenderer alloc]initWithSize:CGSizeMake(288,288) format:f]imageWithActions:^(UIGraphicsImageRendererContext *c){[[UIColor colorWithRed:.12 green:.09 blue:.07 alpha:1]setFill];UIRectFill(CGRectMake(0,0,288,288));[[UIColor colorWithRed:1 green:.47 blue:.16 alpha:1]setFill];[[UIBezierPath bezierPathWithOvalInRect:CGRectMake(44,30,200,200)]fill];[@"TURBO LAB" drawAtPoint:CGPointMake(58,247) withAttributes:@{NSFontAttributeName:[UIFont monospacedSystemFontOfSize:22 weight:UIFontWeightMedium],NSForegroundColorAttributeName:UIColor.whiteColor}];}];_gray=Gray(_cover);
 NSURL *url=[NSURL fileURLWithPath:[NSTemporaryDirectory()stringByAppendingPathComponent:@"turbo-music-original-test.wav"]];dispatch_async(dispatch_get_global_queue(QOS_CLASS_USER_INITIATED,0),^{NSUInteger samples=22050*90;NSMutableData *wav=[NSMutableData dataWithLength:44+samples*2];uint8_t *b=wav.mutableBytes;memcpy(b,"RIFF",4);uint32_t size=(uint32_t)wav.length-8;memcpy(b+4,&size,4);memcpy(b+8,"WAVEfmt ",8);uint32_t fmt=16,rate=22050,bytes=44100;uint16_t pcm=1,channels=1,align=2,bits=16;memcpy(b+16,&fmt,4);memcpy(b+20,&pcm,2);memcpy(b+22,&channels,2);memcpy(b+24,&rate,4);memcpy(b+28,&bytes,4);memcpy(b+32,&align,2);memcpy(b+34,&bits,2);memcpy(b+36,"data",4);size=(uint32_t)samples*2;memcpy(b+40,&size,4);int16_t *out=(void *)(b+44);for(NSUInteger i=0;i<samples;i++){double t=(double)i/22050,beat=fmod(t,.5),freq=220*pow(2,((int)t%4)*2.0/12);out[i]=(int16_t)(1800*sin(2*M_PI*freq*t)*exp(-beat*7));}[wav writeToURL:url options:NSDataWritingAtomic error:nil];dispatch_async(dispatch_get_main_queue(),^{[self installURL:url ticket:ticket];});});
}
- (BOOL)consume:(NSDictionary *)e{return [_bridge consume:e];}
- (BOOL)otaIdle{return !self.playing&&!_bridge.busy&&!_bridge.active;}
- (void)pauseForVoice{if(self.playing){[self play:NO];_status=@"语音会话开始，音乐已暂停";}}
@end
BOOL TMMusicConsume(NSDictionary *e){return [[TMPlayer shared]consume:e];}
BOOL TMMusicPauseForOTA(void){return [[TMPlayer shared]otaIdle];}
void TMMusicPauseForVoice(void){[[TMPlayer shared]pauseForVoice];}
